name: Model Training and Evaluation Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install DVC
        run: pip install dvc

      - name: Configure DVC remote
        run: dvc remote add origin https://dagshub.com/fanerami/dog_cat_classification_v3.dvc

      - name: Pull latest data with DVC
        run: dvc pull

      - name: Check if data has changed
        id: data_changed
        run: |
          git diff --quiet HEAD^ HEAD -- data/
          echo "::set-output name=changed::$(test $? -eq 1)"
        
      - name: Train model
        if: steps.data_changed.outputs.changed == 'true'
        run: echo "train"

      - name: Evaluate model
        run: echo "test"

      - name: Compare and deploy new model
        run: echo "deploy"

